apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 8080  # Le port sur lequel le service sera exposé à l'intérieur du cluster
      targetPort: 8080  # Le port sur lequel votre conteneur écoute
