apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - name: nodejs-port
      protocol: TCP
      port: 8080  
      targetPort: 8080
    - name: react-port
      protocol: TCP
      port: 3000
      targetPort: 3000
