apiVersion: apps/v1
kind: Deployment
metadata:
  name: apapiai-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: danielfebrero/apapiai:prod-latest
        ports:
          - containerPort: 8080
        envFrom:
        - secretRef:
            name: env-secret
      imagePullSecrets:
        - name: my-secret
