apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - name: nodejs-port
      protocol: TCP
      port: 443
      targetPort: 8080
